### ISSUE TITLE
TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.intc'>, <class 'numpy.intc'>]

### ISSUE THREAD

**Issue by zhenyuanzhou** [paulengstler/invisible-stitch#12]
I believe this is also caused by the incompatibility of the packages.

Traceback (most recent call last):
  File "f:\py310ai\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "f:\py310ai\lib\site-packages\gradio\route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\py310ai\lib\site-packages\gradio\blocks.py", line 1710, in process_api
    result = await self.call_function(
  File "f:\py310ai\lib\site-packages\gradio\blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\py310ai\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "f:\py310ai\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "f:\py310ai\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "f:\py310ai\lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
  File "F:\invisible-stitch\run_gradio.py", line 190, in generate_scene
    gs_optimization_bundle, point_cloud = generate_point_cloud(img, prompt)
  File "F:\invisible-stitch\run_gradio.py", line 132, in generate_point_cloud
    optimization_bundle["frames"], point_cloud = extrapolate_point_cloud(prompt, image_size, look_at_params, discard_mask=True, initial_image=initial_image, depth_scaling=0.5, fill_point_cloud_holes=True)
  File "F:\invisible-stitch\run_gradio.py", line 72, in extrapolate_point_cloud
    depth = aligned_depth = infer_with_zoe_dc(zoe_dc_model, t_initial_image, torch.zeros(h, w))
  File "f:\py310ai\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\invisible-stitch\utils\models.py", line 101, in infer_with_zoe_dc
    out = infer_with_pad(zoe_dc, x)
  File "F:\invisible-stitch\utils\models.py", line 84, in infer_with_pad
    out = zoe(x)["metric_depth"]
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\invisible-stitch\zoedepth\models\zoedepth\zoedepth_v1.py", line 156, in forward
    rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\invisible-stitch\zoedepth\models\base_models\midas.py", line 273, in forward
    rel_depth = self.core(x)
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zheny/.cache\torch\hub\intel-isl_MiDaS_master\midas\dpt_depth.py", line 166, in forward
    return super().forward(x).squeeze(dim=1)
  File "C:\Users\zheny/.cache\torch\hub\intel-isl_MiDaS_master\midas\dpt_depth.py", line 114, in forward
    layers = self.forward_transformer(self.pretrained, x)
  File "C:\Users\zheny/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\beit.py", line 15, in forward_beit
    return forward_adapted_unflatten(pretrained, x, "forward_features")
  File "C:\Users\zheny/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\utils.py", line 86, in forward_adapted_unflatten
    exec(f"glob = pretrained.model.{function_name}(x)")
  File "<string>", line 1, in <module>
  File "C:\Users\zheny/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\beit.py", line 125, in beit_forward_features
    x = blk(x, resolution, shared_rel_pos_bias=rel_pos_bias)
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zheny/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\beit.py", line 102, in block_forward
    x = x + self.drop_path(self.gamma_1 * self.attn(self.norm1(x), resolution,
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "f:\py310ai\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zheny/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\beit.py", line 81, in attention_forward
    attn = attn + self._get_rel_pos_bias(window_size)
  File "C:\Users\zheny/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\beit.py", line 47, in _get_rel_pos_bias
    new_sub_table = F.interpolate(old_sub_table, size=(new_height, new_width), mode="bilinear")
  File "f:\py310ai\lib\site-packages\torch\nn\functional.py", line 3924, in interpolate
    raise TypeError(
TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.intc'>, <class 'numpy.intc'>]

**Comment by XuHu0529** [comment]
OK, get it! Thanks for your reply.
